### PR TITLE
Parse 'players' in 'plays' results

### PR DESCRIPTION
**Pull request by cfergeau**
Some quick evening hack, in case it's useful :) This parses the 'players' information in a 'play' request.

### CODE REVIEW

**Comment by ssilva** [comment]
Looks great, Christophe! Thank you for this PR.

I only have one small comment: I think that using parentheses around the player names could be a bit confusing with games that already have them in their names. For instance:
```
2017-04-28: Agricola (Revised Edition) (John Smith - 41, Mary Smith - 46)
```
I think it would be a bit more readable if we used something else... What about square brackets?
```
2017-04-28: Agricola (Revised Edition) [John Smith - 41, Mary Smith - 46]
```

Cheers!

**Comment by cfergeau** [comment]
> I only have one small comment: I think that using parentheses around the player names could be a bit confusing with games that already have them in their names.
>
> I think it would be a bit more readable if we used something else... What about square brackets?

Sure, I've just made that change!

**Comment by cfergeau** [comment]
And also found a bug in the new code :)
```
$ ./bggo  -plays teuf
2020/10/28 21:34:39 ERROR strconv.ParseInt: parsing "start player": invalid syntax
```

**Comment by cfergeau** [comment]
Hmm seems like most fields should be kept as strings :-/ User `edelen` has some scores entered as "1-0-1", this `teuf` user has `start player` in `startposition`, ...

**Comment by ssilva** [comment]
> Hmm seems like most fields should be kept as strings :-/ User `edelen` has some scores entered as "1-0-1", this `teuf` user has `start player` in `startposition`, ...

It is very possible. I observed the same with `rank.Value` and `rank.BayesAverage` [here](https://github.com/ssilva/bggo/blob/9424edd4ad2ae6ab991d79b05d8df2ada3ddfc77/thing.go#L111-L112).

**Pull request merged**
